### PR TITLE
Feature/new firmware

### PR DESCRIPTION
**Pull request by tkazik**
Reason for this PR:
- bump firmware to newest version (which allows [_heading forwarding_](https://support.swiftnav.com/support/solutions/articles/44001907898-rtk-heading-gnss-compass-configuration))
- minor fix for baud rate separation

Depending on https://github.com/ethz-asl/libsbp_catkin/pull/10

### CODE REVIEW

**Comment by tkazik** [comment]
config files still to do? => see https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp/cfg

**Review by michaelpantic — DISMISSED** [review]
LGTM, thanks much!

**Comment by rikba** [comment]
Does that work flawlessly? That's quite awesome :) LGTM

**Comment by rikba** [comment]
Thanks for kicking that off @tkazik . I updated the automatic configuration scripts and tested attitude receiver + reference receiver with heading forwarding. Works well :+1:

**Comment by tkazik** [comment]
sweet...thx for the consistency and merge!

**Pull request merged**
