### PR TITLE
Sarika/inertial

### PR DESCRIPTION
**Pull request by swiftnav-sarika**
With the release of Duro Inertial, the latest firmware v2.1.14 is able to output position during brief GNSS outages using the inertial sensors onboard. This PR is too add these messages to the driver. 
Added support for inertial messages  
	- Added INS flag message in /debug/receiver_state
	- Topic /navsatfix_dr_fix added for dead reckoning fix. 
	- New IMU messages  VelBody, INSStatus, IMU(angular rate and orient quaternion)

Added support for firmware v2.1.14
	- Install compatible SBP library
	- Added messages for with latest SBP version : DeviceMonitor_V2_4_1, UartState_V2_4_1, ReceiverState_V2_4_1

### CODE REVIEW

**Comment by swiftnav-sarika** [comment]
Hi Marco,

Sure, please let us know when the testing is done.
Thank you for your message.

Best,
Sarika

**Comment by marco-tranzatto** [comment]
FYI @swiftnav-sarika PR #63 has been merged and now sbplib 2.4.1 is supported.

**Comment by romleiaj** [comment]
Any update on this? It would be awesome if the Duro Inertial INS solutions were supported.

**Comment by swiftnav-sarika** [comment]
@michaelpantic @rikba, Were you able to test the PR?

**Comment by rikba** [comment]
Please use [piksi_multi_cpp](https://github.com/ethz-asl/ethz_piksi_ros/tree/master/piksi_multi_cpp) with ROS noetic and Piksi Multi Firmware 2.4.16. The Python driver is not maintained and outdated. If you still want to use the Python driver checkout release [v1.10.0](https://github.com/ethz-asl/ethz_piksi_ros/tree/v1.11.0).

We tested the new driver with Piksi Duro and are happy to hear about experience with Piksi Inertial, e.g., testing dead reckoning and [integrating orientation information forwarding](https://github.com/ethz-asl/ethz_piksi_ros/blob/36847701816cb4156faf2e725a2ddd65e75d8a18/piksi_multi_cpp/src/sbp_callback_handler/sbp_callback_handler_relay/ros_enu_relays.cc#L20).

**Pull request closed without merging**
