### PR TITLE
Feature/v2.1.14

### PR DESCRIPTION
**Pull request by rikba**
Updates to Piksi Multi 2.1. Addresses https://github.com/ethz-asl/ethz_piksi_ros/issues/56.

An immediate improvement is incorporation of Galileo, Beidou, and improved SBAS. See https://www.swiftnav.com/resource-files/Piksi%20Multi/v2.0.0/Release%20Notes/PiksiMulti-v2.0.0-ReleaseNotes.pdf and https://www.swiftnav.com/resource-files/Piksi%20Multi/v2.1/Release%20Notes/PiksiMulti-v2.1-ReleaseNotes.pdf.

Features:
- Update SBD to v2.4.1 and Piksi Multi Firmware to v2.1.14
  - Update install script
  - Replace TrackingState with MeasurementState, see https://www.swiftnav.com/resource-files/Piksi%20Multi/v2.0.0/Release%20Notes/PiksiMulti-v2.0.0-ReleaseNotes.pdf
- Replace tagged message names with normal names, e.g. ReceiverState_V2_3_15->ReceiverState.

TODO:
- [x] Test RTK with WiFi corrections
- [x] Test KML offline converter
- [x] Test RTK with XBEE corrections
- [x] Test GUI
- [ ] Update and Readme.md Wiki
- [ ] Update version tag

#### Setup
Roof terrace LEE with base station and single rover. 
screenshot_2018-11-13_22-54-28

- Rover rosbag without DJI: https://polybox.ethz.ch/index.php/s/OxoyosileHvcLci
- Rover rosbag with DJI powered: https://polybox.ethz.ch/index.php/s/JediYLtI2boZQnd

#### Results
- Stable RTK fix even close to house
- Strong satellites including GPS, SBAS, Glonass, Baidou and Galileo on base station using SwiftNav antenna
screenshot_2018-11-13_23-05-57
- Strong satellites including GPS, SBAS, Glonass, and Galileo on rover using Tallysman TW8829
screenshot_2018-11-13_23-26-04
- No drop when powering DJI M600 drone and remote control
- No warnings or error messages

### CODE REVIEW

**Comment by kinergy** [comment]
is this PR going to be integrated sometime?

**Comment by marco-tranzatto** [comment]
@rikba do you have time to apply the changes we discussed about the new message definitions based on firmware version?

**Comment by rikba** [comment]
Hi @marco-tranzatto 
I reverted to the versioned message naming convention. Please have a look. I'll test it in hardware now.

**Comment by marco-tranzatto** [comment]
@kholtmann please check with me as well

**Comment by rikba** [comment]
GUI now also shows Galileo and Beidou satellites.
status_gui
debug_gui

**Comment by rikba** [comment]
Today we also tested this branch with http://store.rfdesign.com.au/rfd-868x-modem/ and it worked well.

**Comment by marco-tranzatto** [comment]
@rikba thanks for your great work! After you approve PR #73 we can merge this PR ;)

**Comment by marco-tranzatto** [comment]
> Today we also tested this branch with http://store.rfdesign.com.au/rfd-868x-modem/ and it worked well. Fix in less than 15 seconds.
> 
> Here is the Wiki https://github.com/ethz-asl/ethz_piksi_ros/wiki/RFD-868x-Modem

Wooow! @kholtmann this radio seems very interesting!

**Pull request merged**
